#!/bin/sh
## Tor Access Point Start/Stop Script
## Starts and stops Tor, adding and removing related IPTables rules to route automatically through Tor
## FIXME - To be obsoleted by the use of the RealTek USB Dongle as a MultiSSID AP instead of the RPi3 built in which only supports a single SSID, so needs Tor to be toggled

test –f /usr/lib/systemd/system/tor.service  || exit 0

case “$1” in
  start)
    echo –n "Starting tor"
    sudo systemctl start tor
    echo "."
    echo -n "Enabling wlan0 routing through tor"
    sudo iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 53 -j REDIRECT --to-ports 53
    sudo iptables -t nat -A PREROUTING -i wlan0 -p tcp --syn -j REDIRECT --to-ports 9040
    echo "."
  ;;
  stop)
    echo –n "Stopping tor"
    sudo systemctl stop stop
    echo "."
    echo -n "Disabling wlan0 routing through tor"
    sudo iptables -t nat -D PREROUTING -i wlan0 -p udp --dport 53 -j REDIRECT --to-ports 53
    sudo iptables -t nat -D PREROUTING -i wlan0 -p tcp --syn -j REDIRECT --to-ports 9040
    echo "."
  ;;
  restart)
    echo –n "Restarting tor"
    sudo systemctl restart tor
    echo "."
  ;;
  reload)
    echo –n "Reloading tor"
    sudo systemctl reload tor
    echo "."
  ;;
  status)
    sudo systemctl status tor
    sudo iptables -L -t nat
  ;;
  *)
    echo "Usage: /opt/piap/torap start|stop|restart|reload|status"
    exit 1
  ;;
esac
