#!/bin/bash
# One-Time config script for backer
# Assumes /dev/sdb1 is /backups device
cryptsetup luksFormat /dev/sdb1
cryptsetup open --type luks /dev/sdb1 backups
mkfs.btrfs /dev/mapper/backups
mkdir /backups
mount /dev/mapper/backups /backups
btrfs subvolume create /@
btrfs subvolume set-default 257 /backups
umount /backups
mount /dev/mapper/backups /backups
snapper -c backups create-config /backups
# snapper config will be managed by salt

